#!/usr/bin/env python

import tf
import rospy
import roslib
import argparse

from geometry_msgs.msg import PoseWithCovarianceStamped

DEFAULT_POSE_SUB = '%s/initialpose'

def handle_robot_pose(msg, robotname):
	br = tf.TransformBroadcaster()
	br.sendTransform((msg.pose.position.x, msg.pose.position.y, msg.pose.position.z),
					 tf.transformations.euler_from_quaternion(msg.pose.orientation.x, msg.pose.orientation.y, msg.pose.orientation.z, msg.pose.orientation.w),
					 rospy.Time.now(),
					 robotname,
					 "world",
					 )

def main():
	robotname = rospy.get_param('robot', '')
	rospy.init_node('multirobot_shapes_tf_broadcaster')
	rospy.Subscriber(DEFAULT_POSE_SUB % robotname,
					 PoseWithCovarianceStamped,
					 handle_robot_pose,
					 robotname
					 )
	rospy.spin()

if __name__ == "__main__":
	roslib.load_manifest('multirobot_shapes')
	main()
